stages:
  - build
  - deploy

default:
  tags:
  - docker
  - jeci

.build:
  stage: build
  image:
    name: python:alpine
    entrypoint: ["/bin/sh", "-c"]
  before_script:
  - pip install -r requirements.txt
  artifacts:
    paths:
      - site/

.deploy:
  stage: deploy
  image:
    name: docker.io/jeci/centos_deployer:latest
  before_script:
    - eval $(ssh-agent -s)
    - ssh-add <(echo "$SSH_PRIVATE_KEY")
    - mkdir -p ~/.ssh
    - 'echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config'

build_stg:
  extends: .build
  script:
  - mkdocs build
  only:
    refs:
      - staging

build_prod:
  extends: .build
  script:
  - mkdocs build
  only:
    refs:
      - prod

deploy_stg:
  extends: .deploy
  script:
    - echo "Deploy to miharu.jeci.xyz"
    - rsync -avz $PWD/site/ "$USER_DEPLOY@miharu.jeci.xyz:/var/www/auth2proxy/stg-pristy-doc/"
  environment:
    name: pristy-fr-stg
    url: https://stg-pristy-doc.jeci.tech
  only:
    refs:
      - staging

deploy_prod:
  extends: .deploy
  script:
    - echo "Deploy to miharu.jeci.xyz"
    - rsync -avz $PWD/site/ "$USER_DEPLOY@miharu.jeci.xyz:/var/www/docs.pristy.fr/"
  environment:
    name: pristy-fr-prod
    url: https://pristy.net/documentation
  only:
    refs:
      - prod
