stages:
  - build
  - deploy

default:
  tags:
  - docker
  - jeci

variables:
  GIT_SUBMODULE_STRATEGY: recursive

.build:
  stage: build
  image:
    name: klakegg/hugo:0.82.0-ext-alpine
    entrypoint: ["/bin/sh", "-c"]
  artifacts:
    paths:
    - documentation/public

.deploy:
  stage: deploy
  image:
    name: docker.io/jeci/centos_deployer:latest
  before_script:
    - eval $(ssh-agent -s)
    - ssh-add <(echo "$SSH_PRIVATE_KEY")
    - mkdir -p ~/.ssh
    - 'echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config'

build_stg:
  extends: .build
  script:
  - hugo -e deploy -s documentation
  only:
    refs:
      - staging

deploy_stg:
  extends: .deploy
  script:
    - echo "Deploy to miharu.jeci.xyz"
    - rsync -avz $PWD/documentation/public/ "$USER_DEPLOY@miharu.jeci.xyz:/var/www/auth2proxy/stg-pristy-doc/"
  environment:
    name: pristy-fr-stg
    url: https://stg-pristy-doc.jeci.tech
  only:
    refs:
      - staging
