site_name: Pristy Documentation
site_author: Jeci SARL
site_description: Documentation pour les utilisateurs de Pristy
copyright: licensed under CC BY 4.0

repo_url: https://gitlab.beezim.fr/jeci/pristy/pristy-documentation
edit_uri: edit/staging/docs/
repo_name: Documentation sur gitlab


# https://squidfunk.github.io/mkdocs-material/
theme:
  name: 'material'
  language: 'fr'
  icon:
    repo: fontawesome/brands/gitlab
  favicon: assets/images/favicon.ico
  logo: assets/logo-pristy-square.png
  font:
    text: Open Sans

  features:
    - navigation.instant
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
    - search.suggest
    - search.share
    - toc.integrate

  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: amber
      accent: pink
      toggle:
        icon: material/weather-sunny
        name: Passer au mode foncé
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: amber
      accent: pink
      toggle:
        icon: material/weather-night
        name: Passer au mode clair
extra:
  search:
    language: 'fr, en'
  social:
    # https://materialdesignicons.com/
    # ls ./.venv/lib/python3.9/site-packages/material/.icons/material/
    - icon: 'material/github'
      link: 'https://github.com/JeciCorp'
    - icon: 'material/twitter'
      link: 'https://twitter.com/JeciCorp'
    - icon: 'material/linkedin'
      link: 'https://www.linkedin.com/company/jeci/'
  alternate:
    #Fonction pour ajouter un switch de language
    - name: French
      link:
      lang: fr
    - name: English
      link: /en/
      lang: en

#Navigation du site
#https://www.mkdocs.org/user-guide/writing-your-docs/#configure-pages-and-navigation
nav:
  - Accueil:
    - 'index.md'
    - Plan du site: 'plan-du-site.md'
  - 'Prise en main':
    - 'se-reperer.md'
    - 'acces-compte.md'
    - 'panneau-lateral.md'
    - 'bandeau-actions.md'
  - 'Gérer son contenu':
    - 'creation-import.md'
    - 'partager.md'
    - 'rechercher.md'
    - 'edition-en-ligne.md'
  - Fonction options:
    - 'options/save-as.md'
    - 'options/OCR.md'
  - Divers:
    - 'format-pris-en-charge.md'
    - 'plan-du-site.md'

plugins:
  - search:
      lang:
        - fr
        - en

# https://squidfunk.github.io/mkdocs-material/extensions/admonition/
# https://squidfunk.github.io/mkdocs-material/extensions/codehilite/
# https://squidfunk.github.io/mkdocs-material/extensions/pymdown/
markdown_extensions:
  - smarty
  - meta
  - sane_lists
  - admonition
  - codehilite
  - toc:
      permalink: ⚓︎
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
  - attr_list
  - md_in_html
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg

use_directory_urls: true
