---
##
#  Copyright 2022 - Jeci SARL - https://jeci.fr

#  Permission is granted to copy, distribute and/or modify this document
#  under the terms of the GNU Free Documentation License, Version 1.3
#  or any later version published by the Free Software Foundation;
#  with no Invariant Sections, no Front-Cover Texts, and no Back-Cover Texts.
#  A copy of the license is included in the section entitled "GNU
#  Free Documentation License".

#  You should have received a copy of the GNU Free Documentation License
#  along with this program.  If not, see http://www.gnu.org/licenses/.
##

site_name: Pristy Documentation
site_author: Jeci SARL
site_description: Documentation pour les utilisateurs de Pristy
copyright: licensed under CC BY 4.0

repo_url: https://gitlab.beezim.fr/jeci/pristy/pristy-documentation
edit_uri: edit/staging/docs/
repo_name: Version accès anticipé


# https://squidfunk.github.io/mkdocs-material/
theme:
  name: 'material'
  language: 'fr'
  icon:
    repo: fontawesome/brands/gitlab
  favicon: assets/images/favicon.png
  logo: assets/logo-pristy-square.png
  font:
    text: Open Sans

  features:
    - navigation.instant
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
    - search.suggest
    - search.share
    - toc.integrate
    - navigation.expand

  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: cyan
      accent: light blue
      toggle:
        icon: material/weather-sunny
        name: Passer au mode foncé
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: cyan
      accent: light blue
      toggle:
        icon: material/weather-night
        name: Passer au mode clair

extra:
  search:
    language: 'fr, en'
  social:
    # https://materialdesignicons.com/
    # ls ./.venv/lib/python3.9/site-packages/material/.icons/material/
    - icon: 'material/github'
      link: 'https://github.com/JeciCorp'
    - icon: 'material/twitter'
      link: 'https://twitter.com/JeciCorp'
    - icon: 'material/linkedin'
      link: 'https://www.linkedin.com/company/jeci/'
  alternate:
    #Fonction pour ajouter un switch de language
    - name: French
      link:
      lang: fr
    - name: English
      link: /en/
      lang: en

#Navigation du site
#https://www.mkdocs.org/user-guide/writing-your-docs/#configure-pages-and-navigation
nav:
  - Accueil:
    - 'index.md'
    - Plan du site: 'plan-du-site.md'
  - 'Pristy app content':
    - 'Prise en main':
      - 'aca/se-reperer.md'
      - 'aca/acces-compte.md'
      - 'aca/panneau-lateral.md'
      - 'aca/bandeau-actions.md'
    - 'Gérer son contenu':
      - 'aca/creation-import.md'
      - 'aca/partager.md'
      - 'aca/rechercher.md'
      - 'aca/edition-en-ligne.md'
      - 'aca/save-as.md'
  - 'Actes Administratifs':
    - 'actes/presentation.md'
    - 'actes/bien-debuter.md'
    - 'actes/imports.md'
    - 'actes/publication.md'
    - 'actes/recherche.md'
  - 'Options':
    - 'options/OCR.md'
  - Divers:
    - 'format-pris-en-charge.md'
    - 'plan-du-site.md'
  - Pristy.fr : "https://pristy.fr/fr/"
  - Contact : "https://pristy.fr/fr/contact"

plugins:
  - search:
      lang:
        - fr
        - en

# https://squidfunk.github.io/mkdocs-material/extensions/admonition/
# https://squidfunk.github.io/mkdocs-material/extensions/codehilite/
# https://squidfunk.github.io/mkdocs-material/extensions/pymdown/
markdown_extensions:
  - abbr
  - smarty
  - meta
  - sane_lists
  - admonition
  - codehilite
  - toc:
      permalink: ⚓︎
      toc_depth: 4
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
  - attr_list
  - md_in_html
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - footnotes

use_directory_urls: true
